# Generated by Django 3.0.7 on 2020-06-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=255)),
                ('duration', models.IntegerField(default=0, help_text='duration in seconds')),
                ('lyrics', models.TextField(blank=True)),
            ],
        ),
    ]
